# Generated by Django 2.2 on 2023-01-04 13:06

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('hno', models.CharField(blank=True, max_length=150, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('workExeperience', jsonfield.fields.JSONField(blank=True, max_length=10000, null=True)),
                ('companyName', models.CharField(blank=True, max_length=150, null=True)),
                ('fromDate', models.CharField(blank=True, max_length=150, null=True)),
                ('toDate', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('qualificiations', jsonfield.fields.JSONField(blank=True, max_length=10000, null=True)),
                ('qualificationName', models.CharField(blank=True, max_length=150, null=True)),
                ('percentage', models.FloatField(default=0.0)),
                ('projects', jsonfield.fields.JSONField(blank=True, max_length=10000, null=True)),
                ('titles', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
