# Generated by Django 2.2 on 2023-01-04 15:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=jsonfield.fields.JSONField(blank=True, max_length=10000, null=True),
        ),
    ]
